apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-deployment.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-provider.yaml
configMapGenerator:
  - name: grafana-dashboards
    namespace: moj-observability
    files:
      - dashboards/vllm-dashboard.json
      - dashboards/moj-search-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
