apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moj-otel-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@github.com-abele-redhat:moj-incub-auth/otel.git
    targetRevision: main
    path: operators
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moj-otel-collector
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@github.com-abele-redhat:moj-incub-auth/otel.git
    targetRevision: main
    path: collector
  destination:
    server: https://kubernetes.default.svc
    namespace: moj-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moj-otel-tracing
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@github.com-abele-redhat:moj-incub-auth/otel.git
    targetRevision: main
    path: tracing
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moj-otel-metrics
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@github.com-abele-redhat:moj-incub-auth/otel.git
    targetRevision: main
    path: metrics
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moj-otel-grafana
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@github.com-abele-redhat:moj-incub-auth/otel.git
    targetRevision: main
    path: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: moj-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
