apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-metrics
  namespace: vllm-serving
  labels:
    app.kubernetes.io/part-of: moj-otel
spec:
  endpoints:
    - port: https
      path: /metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - vllm-serving
  selector:
    matchLabels:
      component: predictor
