apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - opentelemetry-operator-sub.yaml
  - tempo-operator-sub.yaml
  - loki-operator-sub.yaml
  - cluster-logging-sub.yaml
